-- Manual GST module changes
-- Run only statements for columns that do not already exist.

ALTER TABLE tablegstmonthlysnapshot
ADD COLUMN OutputCGSTBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN OutputSGSTBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN OutputIGSTBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN InputCGSTBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN InputSGSTBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN InputIGSTBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN PreviousITCCarryForward DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN ITCUtilizedForIGST DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN ITCUtilizedForCGST DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN ITCUtilizedForSGST DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN CashPayableIGST DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN CashPayableCGST DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN CashPayableSGST DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN VerifiedByUserId VARCHAR(450) NULL,
ADD COLUMN LockedByUserId VARCHAR(450) NULL,
ADD COLUMN LockedOn DATETIME NULL,
ADD COLUMN IsFiledPeriodLocked BIT NOT NULL DEFAULT 0;

UPDATE tablegstmonthlysnapshot
SET OutputCGSTBalance = SalesCGST,
    OutputSGSTBalance = SalesSGST,
    OutputIGSTBalance = SalesIGST,
    InputCGSTBalance = PurchaseCGST,
    InputSGSTBalance = PurchaseSGST,
    InputIGSTBalance = PurchaseIGST
WHERE SnapshotId > 0;

ALTER TABLE tablegstitcrecord
ADD COLUMN Gstr2BMatchStatus VARCHAR(50) NOT NULL DEFAULT 'Pending',
ADD COLUMN MatchedOn DATETIME NULL,
ADD COLUMN MatchedByUserId VARCHAR(450) NULL,
ADD COLUMN MismatchReason VARCHAR(500) NULL,
ADD COLUMN ClaimMonth INT NULL,
ADD COLUMN ClaimYear INT NULL,
ADD COLUMN IsClaimed BIT NOT NULL DEFAULT 0,
ADD COLUMN IsReversed BIT NOT NULL DEFAULT 0,
ADD COLUMN ReversedOn DATETIME NULL,
ADD COLUMN ReversalReason VARCHAR(500) NULL;

ALTER TABLE tablegstreturn
ADD COLUMN FiledByUserId VARCHAR(450) NULL,
ADD COLUMN AcknowledgementNumber VARCHAR(50) NULL;

ALTER TABLE tablegstchallan
ADD COLUMN IGSTPaid DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN CGSTPaid DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN SGSTPaid DECIMAL(18,2) NOT NULL DEFAULT 0;

CREATE INDEX IX_tablegstmonthlysnapshot_Status
ON tablegstmonthlysnapshot (Status);

CREATE INDEX IX_tablegstmonthlysnapshot_Locked
ON tablegstmonthlysnapshot (IsFiledPeriodLocked);
